-- MySQL Script generated by MySQL Workbench
-- Thu Aug 25 19:30:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usario_premium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usario_premium` (
  `idusario_premium` INT NOT NULL AUTO_INCREMENT,
  `descuentos` INT NOT NULL,
  `promociones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusario_premium`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factura_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factura_cliente` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `numero_factura` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `clientes_idcliente` INT NOT NULL,
  PRIMARY KEY (`idfactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transaccion` (
  `idtransaccion` INT NOT NULL AUTO_INCREMENT,
  `numero_cuenta` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `estado` TEXT NOT NULL,
  `usario_premium_idusario_premium` INT NOT NULL,
  `factura_cliente_idfactura` INT NOT NULL,
  PRIMARY KEY (`idtransaccion`),
  UNIQUE INDEX `numero_cuenta_UNIQUE` (`numero_cuenta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metodos_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metodos_pago` (
  `idbanco` INT NOT NULL AUTO_INCREMENT,
  `banco` VARCHAR(45) NOT NULL,
  `tipo_cuenta` VARCHAR(45) NOT NULL,
  `transaccion_idtransaccion` INT NOT NULL,
  PRIMARY KEY (`idbanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nombre_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nombre_usuarios` (
  `idnombre_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `confirmar_contraseña` VARCHAR(45) NOT NULL,
  `metodos_pago_idbanco` INT NOT NULL,
  PRIMARY KEY (`idnombre_usuario`),
  UNIQUE INDEX `idnombre_usuario_UNIQUE` (`idnombre_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_identificacion_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_identificacion_clientes` (
  `idtipo_identificacion` INT NOT NULL AUTO_INCREMENT,
  `tipo_identificacion` VARCHAR(30) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_expedicion` DATE NOT NULL,
  PRIMARY KEY (`idtipo_identificacion`),
  UNIQUE INDEX `idtipo_identificacion_UNIQUE` (`idtipo_identificacion` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `direcciones` (
  `iddirecciones` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `barrio` VARCHAR(45) NOT NULL,
  `observaciones` TEXT NOT NULL,
  PRIMARY KEY (`iddirecciones`),
  UNIQUE INDEX `iddirecciones_UNIQUE` (`iddirecciones` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domiciliarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `domiciliarios` (
  `iddomicilios` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `valor_domicilio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddomicilios`),
  UNIQUE INDEX `iddomicilios_UNIQUE` (`iddomicilios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicio_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicio_cliente` (
  `idservicio_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `disponibles` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idservicio_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empleados` (
  `idempleados` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `domiciliarios_iddomicilios` INT NOT NULL,
  `servicio_cliente_idservicio_cliente` INT NOT NULL,
  PRIMARY KEY (`idempleados`),
  UNIQUE INDEX `idempleados_UNIQUE` (`idempleados` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `correo` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `nombre_usuarios_idnombre_usuario` INT NOT NULL,
  `tipo_identificacion_clientes_idtipo_identificacion` INT NOT NULL,
  `direcciones_iddirecciones` INT NOT NULL,
  `empleados_idempleados` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fechas_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fechas_productos` (
  `idfechas_productos` INT NOT NULL AUTO_INCREMENT,
  `fecha_vencimiento` DATETIME NOT NULL,
  `estado` TEXT NOT NULL,
  PRIMARY KEY (`idfechas_productos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `encargado_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `encargado_bodega` (
  `idencargadobodega` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `disponibles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idencargadobodega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bodega` (
  `idbodega` INT NOT NULL AUTO_INCREMENT,
  `nombre_bodega` VARCHAR(45) NOT NULL,
  `entrada_bodega` DATETIME NOT NULL,
  `salida` DATETIME NOT NULL,
  `pruductos` VARCHAR(30) NOT NULL,
  `cantidad` INT NOT NULL,
  `fechas_productos_idfechas_productos` INT NOT NULL,
  `encargado_bodega_idencargadobodega` INT NOT NULL,
  PRIMARY KEY (`idbodega`),
  UNIQUE INDEX `idbodega_UNIQUE` (`idbodega` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorias` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `tipo_categoria` VARCHAR(45) NOT NULL,
  `bodega_idbodega` INT NOT NULL,
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) VISIBLE,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios` (
  `idinventarios` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NOT NULL,
  `unidades_existente` INT NOT NULL,
  `fecha_entrada` DATETIME NOT NULL,
  `productos_entrada` INT NOT NULL,
  `total_productos` INT NOT NULL,
  PRIMARY KEY (`idinventarios`),
  UNIQUE INDEX `idinventarios_UNIQUE` (`idinventarios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `numero_pedidos` INT NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `fecha_envio` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `domiciliarios_iddomicilios` INT NOT NULL,
  `clientes_idcliente` INT NOT NULL,
  PRIMARY KEY (`idpedidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pais` (
  `idpais` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  `zona_horaria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  `pais_idpais` INT NOT NULL,
  PRIMARY KEY (`iddepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciudad` (
  `idciudad` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `departamento_iddepartamento` INT NOT NULL,
  `clientes_idcliente` INT NOT NULL,
  PRIMARY KEY (`idciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `factura_cliente_idfactura` INT NOT NULL,
  `inventarios_idinventarios` INT NOT NULL,
  `pedidos_idpedidos` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `idproducto_UNIQUE` (`idproducto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_proveedores` (
  `idempresa_proveedores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `inicio_contrato` DATETIME NOT NULL,
  `fin_contrato` DATETIME NOT NULL,
  PRIMARY KEY (`idempresa_proveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proovedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proovedores` (
  `idproovedores` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `nit_empresa` INT NOT NULL,
  `empresa_proveedores_idempresa_proveedores` INT NOT NULL,
  PRIMARY KEY (`idproovedores`),
  UNIQUE INDEX `idproovedores_UNIQUE` (`idproovedores` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factura_proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factura_proveedores` (
  `idfactura_proveedores` INT NOT NULL AUTO_INCREMENT,
  `numero_factura` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `proovedores_idproovedores` INT NOT NULL,
  `encargado_bodega_idencargadobodega` INT NOT NULL,
  PRIMARY KEY (`idfactura_proveedores`),
  UNIQUE INDEX `idfactura_proveedores_UNIQUE` (`idfactura_proveedores` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipo_identificacion_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipo_identificacion_empleados` (
  `idtipo_identificacion_empleados` INT NOT NULL AUTO_INCREMENT,
  `tipo_identificacion` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `fecha_expedicion` DATE NOT NULL,
  `empleados_idempleados` INT NOT NULL,
  PRIMARY KEY (`idtipo_identificacion_empleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios_has_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios_has_bodega` (
  `inventarios_idinventarios` INT NOT NULL,
  `bodega_idbodega` INT NOT NULL,
  PRIMARY KEY (`inventarios_idinventarios`, `bodega_idbodega`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
